/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package segachafa;

import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileWriter;
import java.io.FilenameFilter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.jdom2.Document;
import org.jdom2.Element;
import org.jdom2.JDOMException;
import org.jdom2.input.SAXBuilder;
import org.jdom2.output.Format;
import org.jdom2.output.XMLOutputter;

/**
 *
 * @author victo
 */
public class EditarSolicitud extends javax.swing.JFrame {

    String UUID;

    /**
     * Creates new form EditarSolicitud
     */
    public EditarSolicitud() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxtProgramaEd = new javax.swing.JTextField();
        TxtGrupo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TxtObservaciones = new javax.swing.JTextField();
        ComboBox = new javax.swing.JComboBox<>();
        BtnAceptarAnidado = new javax.swing.JButton();
        BtnVolver = new javax.swing.JButton();
        BtnCrear = new javax.swing.JButton();
        CheckAlta = new javax.swing.JRadioButton();
        CheckBaja = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        TxtMateria = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxtMatricula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TxtProgramaEd.setEnabled(false);

        TxtGrupo.setEnabled(false);

        jLabel4.setText("Grupo");

        jLabel5.setText("Observaciones");

        TxtObservaciones.setEnabled(false);

        ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboBox.setEnabled(false);
        ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxActionPerformed(evt);
            }
        });

        BtnAceptarAnidado.setText("Aceptar");
        BtnAceptarAnidado.setEnabled(false);
        BtnAceptarAnidado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAceptarAnidadoActionPerformed(evt);
            }
        });

        BtnVolver.setText("Volver");
        BtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverActionPerformed(evt);
            }
        });

        BtnCrear.setText("Aceptar");
        BtnCrear.setEnabled(false);
        BtnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCrearActionPerformed(evt);
            }
        });

        CheckAlta.setText("Alta");
        CheckAlta.setEnabled(false);
        CheckAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckAltaActionPerformed(evt);
            }
        });

        CheckBaja.setText("Baja");
        CheckBaja.setEnabled(false);
        CheckBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBajaActionPerformed(evt);
            }
        });

        jLabel1.setText("Materia");

        TxtMateria.setEnabled(false);

        jLabel2.setText("Matricula");

        TxtMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtMatriculaActionPerformed(evt);
            }
        });
        TxtMatricula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtMatriculaKeyPressed(evt);
            }
        });

        jLabel3.setText("Programa Educativo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CheckAlta)
                        .addGap(27, 27, 27)
                        .addComponent(CheckBaja)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtObservaciones, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TxtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtMateria, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TxtProgramaEd, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(63, 63, 63)
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(TxtGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BtnAceptarAnidado)
                                        .addGap(71, 71, 71))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BtnCrear)
                        .addGap(218, 218, 218)
                        .addComponent(BtnVolver)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckAlta)
                    .addComponent(CheckBaja))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TxtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtProgramaEd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(TxtGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(BtnAceptarAnidado))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnCrear)
                    .addComponent(BtnVolver))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxActionPerformed
        BtnAceptarAnidado.setEnabled(true);
    }//GEN-LAST:event_ComboBoxActionPerformed

    private void BtnAceptarAnidadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAceptarAnidadoActionPerformed
        String ArchivoMateria = (String) ComboBox.getSelectedItem();
        SAXBuilder builder = new SAXBuilder();
        //System.out.println("prueba:   "+ "src/segachafa/movimientos/" + ArchivoMateria);
        File xmlFile = new File("src/segachafa/movimientos/" + ArchivoMateria);

        try {

            Document documentoXMLRead = (Document) builder.build(xmlFile);
            Element rootNode = documentoXMLRead.getRootElement();
            List list = rootNode.getChildren();

            for (int i = 0; i < list.size(); i++) {

                Element node = (Element) list.get(i);

                if (node.getName() == "Materia") {
                    TxtMateria.setEnabled(true);
                    TxtMateria.setText(node.getText());
                } else if (node.getName() == "Grupo") {
                    TxtGrupo.setEnabled(true);
                    TxtGrupo.setText(node.getText());
                } else if (node.getName() == "TipoMovimiento") {
                    if (node.getText() == "Alta") {
                        CheckAlta.setSelected(true);
                        CheckBaja.setSelected(false);
                    } else {
                        CheckBaja.setSelected(true);
                        CheckAlta.setSelected(false);
                    }
                } else if (node.getName() == "Observaciones") {
                    TxtObservaciones.setEnabled(true);
                    TxtObservaciones.setText(node.getText());
                } else if (node.getName() == "UUID") {
                    UUID = node.getText();
                } else {
                }
            }

        } catch (IOException io) {
            System.out.println(io.getMessage());
        } catch (JDOMException jdomex) {
            System.out.println(jdomex.getMessage());
        }

        //Aqui lee el de solicitud para obtener el programa educativo
        //System.out.println("ruta: " + "src/segachafa/solicitudes/" + ArchivoMateria.substring(0, 6) + "-" + ArchivoMateria.substring(ArchivoMateria.indexOf('%') + 1,ArchivoMateria.indexOf('@') +1) + ArchivoMateria.substring(ArchivoMateria.indexOf('@') + 1));
        File xmlFilePE = new File("src/segachafa/solicitudes/" + ArchivoMateria.substring(0, 6) + "-" + ArchivoMateria.substring(ArchivoMateria.indexOf('#') + 1));

        try {

            Document documentoXMLRead = (Document) builder.build(xmlFilePE);
            Element rootNode = documentoXMLRead.getRootElement();
            List list = rootNode.getChildren();

            for (int i = 0; i < list.size(); i++) {

                Element node = (Element) list.get(i);
                if (node.getName() == "ProgramaEducativo") {
                    TxtProgramaEd.setEnabled(true);
                    TxtProgramaEd.setText(node.getText());
                } else {
                }
            }

        } catch (IOException io) {
            System.out.println(io.getMessage());
        } catch (JDOMException jdomex) {
            System.out.println(jdomex.getMessage());
        }
        BtnAceptarAnidado.setEnabled(false);
        CheckAlta.setEnabled(true);
        CheckBaja.setEnabled(true);
        BtnCrear.setEnabled(true);
        TxtProgramaEd.setEnabled(false);
    }//GEN-LAST:event_BtnAceptarAnidadoActionPerformed

    private void BtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverActionPerformed
        this.setVisible(false);
        Principal Principal = new Principal();
        Principal.setVisible(true);
        Principal.setLocationRelativeTo(null);
    }//GEN-LAST:event_BtnVolverActionPerformed

    private void BtnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCrearActionPerformed
        if (CheckAlta.isSelected() != true && CheckBaja.isSelected() != true) {
            JOptionPane.showMessageDialog(this, "El tipo de movimiento no se ha seleccionado");
        } else if (TxtMatricula.getText().length() <= 0) {
            JOptionPane.showMessageDialog(this, "El campo de la matricula tiene que estar lleno");
        } else if (TxtGrupo.getText().length() <= 0) {
            JOptionPane.showMessageDialog(this, "El campo del grupo tiene que estar lleno");
        } else if (TxtProgramaEd.getText().length() <= 0) {
            JOptionPane.showMessageDialog(this, "El campo del programa educativo tiene que estar lleno");
        } else if (TxtMateria.getText().length() <= 0) {
            JOptionPane.showMessageDialog(this, "El campo de la materia tiene que estar lleno");
        } else {
            String ArchivoMateria = (String) ComboBox.getSelectedItem();
            Path path = Paths.get("src/segachafa/movimientos/" + ArchivoMateria);
            String TipoMovimiento;
            if (CheckAlta.isSelected()) {
                TipoMovimiento = "Alta";
            } else {
                TipoMovimiento = "Baja";
            }
            try {
                Files.delete(path);
            } catch (IOException ex) {
                Logger.getLogger(EliminarSolicitud.class.getName()).log(Level.SEVERE, null, ex);
            }

            String IdUnicoMateria = ArchivoMateria;
            Element childUUIDMovimiento = new Element("UUID");
            childUUIDMovimiento.addContent(UUID);
            Element Movimiento = new Element("Movimiento");
            Document docMovimientos = new Document();
            Element childMateria = new Element("Materia");
            childMateria.addContent(TxtMateria.getText());
            Element childGrupo = new Element("Grupo");
            childGrupo.addContent(TxtGrupo.getText());
            Element childTipoMov = new Element("TipoMovimiento");
            childTipoMov.addContent(TipoMovimiento);
            Element childObservaciones = new Element("Observaciones");
            childObservaciones.addContent(TxtObservaciones.getText());

            Movimiento.addContent(childUUIDMovimiento);
            Movimiento.addContent(childMateria);
            Movimiento.addContent(childGrupo);
            Movimiento.addContent(childTipoMov);
            Movimiento.addContent(childObservaciones);

            docMovimientos.setRootElement(Movimiento);
            XMLOutputter outter = new XMLOutputter();
            outter.setFormat(Format.getPrettyFormat());

            try {
                outter.output(docMovimientos, new FileWriter(new File("src/segachafa/movimientos/" + IdUnicoMateria)));
            } catch (IOException ex) {
                Logger.getLogger(CrearSolicitud.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(this, "Solicitud modificada con exito!");
        }
    }//GEN-LAST:event_BtnCrearActionPerformed

    private void CheckAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckAltaActionPerformed
        CheckBaja.setSelected(false);
    }//GEN-LAST:event_CheckAltaActionPerformed

    private void CheckBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBajaActionPerformed
        CheckAlta.setSelected(false);
    }//GEN-LAST:event_CheckBajaActionPerformed

    private void TxtMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtMatriculaActionPerformed

    private void TxtMatriculaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtMatriculaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (TxtMatricula.getText().length() < 6 || TxtMatricula.getText().length() > 6) {
                JOptionPane.showMessageDialog(this, "La matricula tiene que ser de 6 digitos");
            } else {
                ComboBox.removeAllItems();

                File root = new File("src/segachafa/movimientos/");
                FilenameFilter beginswithm = new FilenameFilter() {
                    public boolean accept(File directory, String filename) {
                        return filename.startsWith(TxtMatricula.getText());
                    }
                };

                File[] files = root.listFiles(beginswithm);
                for (File f : files) {
                    String NombreArchivo = f.toString();
                    //ComboBox.addItem(NombreArchivo.substring(26, NombreArchivo.indexOf("@", 1)));
                    ComboBox.addItem(NombreArchivo.substring(26));
                }
                BtnAceptarAnidado.setEnabled(true);
                ComboBox.setEnabled(true);
            }
        }
    }//GEN-LAST:event_TxtMatriculaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarSolicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarSolicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarSolicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarSolicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarSolicitud().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAceptarAnidado;
    private javax.swing.JButton BtnCrear;
    private javax.swing.JButton BtnVolver;
    private javax.swing.JRadioButton CheckAlta;
    private javax.swing.JRadioButton CheckBaja;
    private javax.swing.JComboBox<String> ComboBox;
    private javax.swing.JTextField TxtGrupo;
    private javax.swing.JTextField TxtMateria;
    private javax.swing.JTextField TxtMatricula;
    private javax.swing.JTextField TxtObservaciones;
    private javax.swing.JTextField TxtProgramaEd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
